"""user to user rework

Revision ID: 3c484261a1e1
Revises: 47149badfccb
Create Date: 2022-05-04 00:14:59.834802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c484261a1e1'
down_revision = '47149badfccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
