"""added cheers(analog for likes) to publication class

Revision ID: c4e7aa02f372
Revises: 3c484261a1e1
Create Date: 2022-05-04 21:15:21.587783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e7aa02f372'
down_revision = '3c484261a1e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association',
    sa.Column('publications', sa.Integer(), nullable=True),
    sa.Column('users', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['publications'], ['publications.id'], ),
    sa.ForeignKeyConstraint(['users'], ['users.id'], )
    )
    op.drop_column('publications', 'cheers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('publications', sa.Column('cheers', sa.INTEGER(), nullable=True))
    op.drop_table('association')
    # ### end Alembic commands ###
