"""swaped subscriptions and subscribers in user class

Revision ID: f20f979477ca
Revises: c6b7aee2ac1a
Create Date: 2022-05-03 22:45:57.600636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20f979477ca'
down_revision = 'c6b7aee2ac1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
