"""user to user hotfix №1

Revision ID: f6dfe7b00ce7
Revises: f20f979477ca
Create Date: 2022-05-03 23:43:00.158779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6dfe7b00ce7'
down_revision = 'f20f979477ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
